name: Sync repo

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  schedule:
    - cron: 0 0 * * *
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: sync
      uses: actions/checkout@master
    - name: Make commits
      run: |
          python3 xml2http.py
          curl -H 'Content-Type:text/plain' --data-binary @baidu_urls.txt " ${{ secrets.BAIDU_TOKEN}}"
          date >> time.txt
          git config --global user.name "Github Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Update my blog urls to baidu."
          git push
